# File: .github/workflows/OIDC_workflow.yml

name: "Azure Login with OIDC"
on: workflow_dispatch

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Azure CLI script
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group list
