name: github repo create
on:
  workflow_dispatch:
    inputs:
      TFACTION:
        default: "apply"
        required: true
        type: choice
        options:
         - "apply"
         - "destroy"
permissions:
  id-token: write  
  contents: write
  actions: write
  repository-projects: write
env:
  TF_HTTP_USERNAME: '${{ secrets.GITLAB_USER }}'
  TF_HTTP_ADDRESS: '${{ secrets.GITLAB_URL }}/gitproj'
  TF_HTTP_PASSWORD: '${{ secrets.GITLAB_TOKEN }}'
  
jobs:
  repo_create:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    name: 'setup repo'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: env print
        run: env
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform  init
        working-directory: terraform/github

      - name: Terraform Plan
        run: terraform  plan 
        working-directory: terraform/github
      - name: Terraform Apply
        if: ${{ github.event.inputs.TFACTION == 'apply' }}
        run: terraform  apply --auto-approve 
        working-directory: terraform/github

      - name: Terraform Destroy
        if: ${{ github.event.inputs.TFACTION == 'destroy' }}
        run: terraform destroy --auto-approve
        working-directory: terraform/github

