name: "VNET peering Lab"
on:
  workflow_dispatch:
    inputs:
      TFACTION:
        description: "Terraform Action"
        default: "apply"
        required: true
        type: choice
        options:
         - "apply"
         - "destroy"
         
permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  vmsetup:
    runs-on: ubuntu-latest
 # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    name: 'labsetup'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform  init
        working-directory: terraform/vnetpeer

    # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform  plan -input=false
        working-directory: terraform/vnetpeer

      - name: Terraform Apply
        if: ${{ github.event.inputs.TFACTION == 'apply' }}
        run: terraform  apply --auto-approve -input=false
        working-directory: terraform/vnetpeer
      - name: Terraform Destroy
        if: ${{ github.event.inputs.TFACTION == 'destroy' }}
        run: terraform destroy --auto-approve -input=false
        working-directory: terraform/vnetpeer
