name: setup vm lab
on:
  workflow_dispatch:
    inputs:
      TFACTION:
        default: "apply"
        required: true
        type: choice
        options:
         - "apply"
         - "destroy"
      VMCOUNT:
         default: "2"
         required: true
         type: text
         
permissions:
  contents: 'read'
  id-token: 'write'
env:
  TF_HTTP_USERNAME: '${{ secrets.GITLAB_USER }}'
  TF_HTTP_ADDRESS: '${{ secrets.GITLAB_URL }}/azurevm'
  TF_HTTP_PASSWORD: '${{ secrets.GITLAB_TOKEN }}'
  TF_VAR_VMCOUNT: '${{ github.event.inputs.VMCOUNT }}'
  
jobs:
  vmsetup:
    runs-on: mylab-docker
    name: 'labsetup'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5
      - name: Terraform Init
        run: terraform  init
        working-directory: terraform/rgvnetvm


      - name: Terraform Plan
        run: terraform  plan -input=false
        working-directory: terraform/rgvnetvm

      - name: Terraform Apply
        if: ${{ github.event.inputs.TFACTION == 'apply' }}
        run: terraform  apply --auto-approve -input=false
        working-directory: terraform/rgvnetvm
        
      - name: Terraform Destroy
        if: ${{ github.event.inputs.TFACTION == 'destroy' }}
        run: terraform destroy --auto-approve -input=false
        working-directory: terraform/rgvnetvm
